'use strict';
const $=id=>document.getElementById(id);
const locations={hall:'礼堂',library:'图书馆',restricted:'禁书区',potions:'魔药教室',greenhouse:'温室',lake:'黑湖',pitch:'魁地奇球场',forest:'禁林入口',hospital:'校医院',hogsmeade:'霍格莫德入口'};
const spells={lumos:['荧光闪烁','wand'],nox:['诺克斯','wand'],wingardium_leviosa:['漂浮咒','feather'],accio:['飞来咒','feather'],alohomora:['阿拉霍洞开','chest'],reparo:['修复如初','cup'],scourgify:['清理一新','cauldron'],aguamenti:['清水如泉','plant'],protego:['盔甲护身','self'],expelliarmus:['除你武器','dummy']};
const objectNames={feather:'练习羽毛',chest:'练习箱',cup:'破损杯子',cauldron:'坩埚',plant:'银叶草',dummy:'练习假人'};
const toolNames={sleep:'休息与起床',move:'沿路前行',wait:'等待',attend_class:'完成课堂',study:'学习魔咒',practice_spell:'练习魔咒',cast_spell:'施放魔咒',talk:'交谈',ask:'询问',give:'赠礼',use_item:'使用物品',read:'阅读',search:'搜索',inspect:'观察'};
let credential=localStorage.getItem('hogwarts-key')||'', view=null, activeNpc=null, busy=false;
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls){const b=node('button',text,cls);b.onclick=fn;return b;}
async function api(path,body){const res=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(credential?{Authorization:'Bearer '+credential}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error||'暂时无法完成，请稍后重试。');return data;}
async function refresh(){view=await api('/api/state');render();}
function rememberKey(key){credential=key;localStorage.setItem('hogwarts-key',key);}
function log(text,time,error=false){const row=node('div',undefined,'log-entry'+(error?' error':''));row.append(node('small',time||'校园提示'),node('p',text));$('log').prepend(row);while($('log').children.length>40)$('log').lastElementChild.remove();}
function describe(tool,result){if(result.reply)return result.reply;if(result.discovery)return result.discovery;if(result.learned_fact)return result.learned_fact;if(result.learned_spells)return '课堂结束。你学会了：'+result.learned_spells.map(x=>spells[x][0]).join('、')+'。';if(result.spell)return result.success===undefined?'熟练度提升至 '+result.proficiency+'。':result.success?spells[result.spell][0]+'已经生效。':result.effect;if(result.learned)return '你学会了'+spells[result.learned][0]+'。';if(result.name&&result.location)return '来到'+result.name+'。';if(result.awake)return '你醒了，体力为 '+result.stamina+'。';if(result.used)return '使用物品后，体力为 '+result.stamina+'。';if(result.waited_minutes)return '等待了 '+result.waited_minutes+' 分钟。';if(result.books)return '找到《校园植物笔记》，现在可以阅读。';if(result.chapters)return '练习册有十种基础魔咒。读目录后，仍须在图书馆学习。';if(result.description)return result.description;if(result.state)return Object.entries(result.state).map(([k,v])=>({locked:'是否上锁',opened:'是否打开',broken:'是否破损',dirty:'是否脏污',watered:'是否浇水',armed:'是否持有武器',levitating:'是否悬浮',summoned:'是否已召到面前'}[k]||k)+'：'+(v?'是':'否')).join('；');return '行动完成。';}
async function act(tool,args={}){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await api('/api/action',{tool,arguments:args});const text=describe(tool,r.result);log((toolNames[tool]||'校园行动')+' · '+text,r.time);for(const notice of r.notices)log(notice,r.time);if(['talk','ask','give'].includes(tool)){const reply=node('p',text,'reply');$('dialog-reply').replaceChildren(reply);}await refresh();}catch(e){log(e.message,'行动未完成',true);if($('conversation').open)$('dialog-reply').replaceChildren(node('p',e.message,'error'));}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);if(view)render();}}
function render(){if(!view)return;$('welcome').hidden=true;$('game').hidden=false;$('logout').hidden=false;const p=view.status.result,s=view.scene.result;
 $('student-name').textContent=p.name+'的学期';$('clock').textContent=view.status.time.replace('T',' · ')+'　拉文克劳 · '+p.year+' 年级';
 $('metrics').replaceChildren(...[['体力',p.stamina+'/100'],['金币',p.coins],['学院分',p.house_points],['已学魔咒',Object.keys(p.learned_spells).length],['违规记录',p.violations.length]].map(([name,value])=>{const x=node('div',undefined,'metric');x.append(node('small',name),node('strong',String(value)));return x;}));
 $('location-name').textContent=s.name;$('description').textContent=s.description;
 const actions=$('awake-actions');actions.replaceChildren();if(p.sleeping)actions.append(button('起床，开始今天',()=>act('sleep',{hours:0}),'primary'));else{actions.append(button('等待 10 分钟',()=>act('wait',{minutes:10})),button('等待 1 小时',()=>act('wait',{minutes:60})));if(p.location==='hospital')actions.append(button('休息 8 小时',()=>act('sleep',{hours:8})));if(p.location==='library')actions.append(button('搜索书架',()=>act('search',{target:'shelves'})),button('阅读植物笔记',()=>act('read',{item:'library_book'})),button('搜索练习箱',()=>act('search',{target:'chest'})));}
 $('exits').replaceChildren(...s.exits.map(x=>{const b=button('→ '+x.name,()=>act('move',{destination:x.id}));b.disabled=p.sleeping;return b;}));
 $('npcs').replaceChildren(...s.npcs.map(n=>{const row=node('div',undefined,'npc-row');const title=node('span',n.name);title.append(node('span',n.role,'badge'));row.append(title,button('与 TA 交谈',()=>openNpc(n)));return row;}));if(!s.npcs.length)$('npcs').append(node('p','这里暂时没有人。','fine'));
 $('objects').replaceChildren(...s.objects.map(x=>button(objectNames[x]||x,()=>act('inspect',{target:x}))));$('object-section').hidden=!s.objects.length;
 $('map').replaceChildren(...Object.entries(locations).map(([id,name])=>button(name,()=>{$('map-note').textContent=id===p.location?'你就在这里。':s.exits.some(e=>e.id===id)?'这个地点与当前位置相连，可从上方「可以前往」移动。':'请沿校园出口逐步前往。';},'map-place'+(id===p.location?' current':s.exits.some(e=>e.id===id)?' adjacent':''))));
 $('schedule').replaceChildren(...view.schedule.result.classes.map(c=>{const row=node('div',undefined,'class-row');row.append(node('strong',c.name),node('small',c.start.slice(11)+' · '+locations[c.location]));if(c.location===p.location&&!p.sleeping)row.append(button('签到上课',()=>act('attend_class',{course:c.id})));return row;}));if(!view.schedule.result.classes.length)$('schedule').append(node('p','周末，没有课程。','fine'));
 $('spells').replaceChildren(...Object.entries(spells).map(([id,[name,target]])=>{const level=p.learned_spells[id],row=node('div',undefined,'spell-row');row.append(node('span',name),node('small',level?'熟练度 '+level+'/5':'尚未学会'));const tools=node('div',undefined,'actions');if(level&&!p.sleeping){tools.append(button('练习',()=>act('practice_spell',{spell:id})));if(['self','wand',...s.objects].includes(target))tools.append(button('施放',()=>act('cast_spell',{spell:id,target})));}else if(!level&&!p.sleeping&&['library','restricted'].includes(p.location))tools.append(button('用课本学习',()=>act('study',{spell:id})));row.append(tools);return row;}));
 $('inventory').replaceChildren(...view.inventory.result.map(i=>{const row=node('div',undefined,'item-row');row.append(node('span',i.name+' × '+i.quantity));if(['apple','tonic'].includes(i.id))row.append(button('使用',()=>act('use_item',{item:i.id})));if(i.id==='textbook')row.append(button('阅读',()=>act('read',{item:i.id})));return row;}));
 $('facts').replaceChildren(...(p.known_facts.length?p.known_facts.map(f=>node('p',f)): [node('p','尚无见闻。与人交谈，或读一读书。','fine')]));
 $('students').replaceChildren(...view.students.map(x=>node('p',x.name+' · '+locations[x.location],'fine')));
}
function openNpc(n){activeNpc=n;$('dialog-name').textContent=n.name+' · '+n.role;$('message').value='';$('dialog-reply').replaceChildren();$('dialog-options').replaceChildren(button('打声招呼',()=>act('talk',{npc:n.id,message:'你好，我想了解校园生活。'})),button('送一颗苹果',()=>act('give',{npc:n.id,item:'apple'})));if(n.id==='professor')$('dialog-options').append(button('申请禁书区许可',()=>act('ask',{npc:n.id,topic:'permission'})));if(n.id==='merchant')$('dialog-options').append(button('购买恢复药剂 · 5 金币',()=>act('ask',{npc:n.id,topic:'buy tonic'})));$('conversation').showModal();}
$('send-message').onclick=()=>{const message=$('message').value.trim();if(message&&activeNpc)act('talk',{npc:activeNpc.id,message});};
$('register').onclick=async()=>{try{const r=await api('/api/register',{name:$('name').value});rememberKey(r.api_key);await refresh();log('学生凭证已领取。请点「复制学生凭证」保存，也可让 AI 使用同一账号。');}catch(e){$('entry-error').textContent=e.message;}};
$('login').onclick=async()=>{const input=$('credential').value.trim();if(!input.startsWith('hw_sk_')){$('entry-error').textContent='请只粘贴 hw_sk_ 开头的凭证。';return;}rememberKey(input);try{await refresh();}catch(e){$('entry-error').textContent=e.message;}};
$('logout').onclick=()=>{credential='';localStorage.removeItem('hogwarts-key');location.href='/';};
async function copy(text){try{await navigator.clipboard.writeText(text);log('已复制，请妥善保存。');}catch{const input=node('textarea');input.value=text;$('log').prepend(input);input.select();log('浏览器未允许复制。请复制上方文本。');}}
$('copy-key').onclick=()=>copy(credential);
$('copy-mcp').onclick=()=>copy(location.origin+'/mcp/?api_key='+encodeURIComponent(credential));
if(credential)refresh().catch(e=>{$('entry-error').textContent=e.message;});
setInterval(()=>{if(view&&!busy&&!document.hidden)refresh().catch(()=>{});},10000);
