import {state,update,subscribe,saveKey} from "./store.js";import {api} from "./api.js";import {el,toast} from "./ui/dom.js";import {hud} from "./hud.js";import {map} from "./map.js";import {scene} from "./scenes/place.js";
async function refresh(){update(await api.state())}
async function act(tool,command){if(state.busy)return;state.busy=true;el("game").setAttribute("aria-busy","true");try{const result=await api.action(tool,command);toast(result.result?.message||"行动已记入仙途。");await refresh()}catch(error){toast(error.message)}finally{state.busy=false;el("game").setAttribute("aria-busy","false")}}
subscribe(data=>{el("welcome").hidden=true;el("game").hidden=false;el("logout").hidden=false;el("watch-note").hidden=true;hud(data);map(data,act);scene(data,act);el("log").replaceChildren();for(const entry of [...data.history.result].reverse()){const p=document.createElement("p");const label={rename:"改名",choose_route:"择道",travel:"行路",cultivate:"修炼",explore:"探索",talk:"交谈",fight:"斗法",use_skill:"招式",breakthrough:"突破",craft:"炼制",trade:"交易",quest_step:"任务推进",incident_resolve:"处置事件"}[entry.action]||"仙途记录";p.textContent="第 "+(Math.floor(entry.time/1440)+1)+" 日 · "+label;const detail=document.createElement("small");detail.textContent=" · "+(entry.result?.message||entry.result?.name||entry.result?.gained!==undefined&&"修为增加 "+entry.result.gained||entry.result?.outcome||entry.result?.log?.map(x=>(x.actor==="player"?"我方":x.actor==="beast"?"灵兽":"对手")+" "+(data.world.result.skills[x.skill]?.name||x.skill||x.item||"")+(x.damage!==undefined?" · 伤害 "+x.damage:x.hit===false?" · 未命中":x.skipped?" · 受控":"")).join("；")||"已记录");p.append(detail);el("log").append(p)}});
const routeNotes={qingxiao:"剑先问心，再问敌。实战与机动。",xuanheng:"天地有序，万物可解。预阵与秘境破解。",danxia:"药可以救人，也可以杀人。丹品与医修。",fuyao:"与灵兽同行，在狩猎和共存间作出选择。",rogue:"没有山门，也有自己的路。混合流派与奇遇。"};
el("route").onchange=()=>el("route-note").textContent=routeNotes[el("route").value];el("route").onchange();
el("register").onclick=async()=>{try{const data=await api.register(el("name").value,el("route").value);saveKey(data.api_key);await refresh();toast("已入岛，请保存凭证。人类与AI使用这同一个号。")}catch(error){el("entry-error").textContent=error.message}};
el("login").onclick=async()=>{try{saveKey(el("key").value.trim());await refresh()}catch(error){el("entry-error").textContent=error.message}};
el("logout").onclick=()=>{saveKey("");state.data=null;el("welcome").hidden=false;el("game").hidden=true;el("logout").hidden=true;el("key").value=""};
el("open-ai").onclick=()=>{el("ai-dialog").showModal();if(state.key){el("ai-key").value=state.key;el("ai-url").value=location.origin+"/mcp/";el("ai-result").hidden=false;el("ai-create").hidden=true}else{el("ai-create").hidden=false;el("ai-result").hidden=true}};
el("register-ai").onclick=async()=>{try{const data=await api.register(el("ai-name").value,null,"ai");saveKey(data.api_key);el("ai-key").value=data.api_key;el("ai-url").value=location.origin+"/mcp/";el("ai-result").hidden=false;await refresh()}catch(error){el("ai-error").textContent=error.message}};
async function copy(value){try{await navigator.clipboard.writeText(value);toast("已复制。")}catch{toast("请手动选中保存。")}}
el("copy-key").onclick=()=>copy(state.key);el("copy-ai").onclick=()=>copy(JSON.stringify({url:el("ai-url").value,headers:{Authorization:"Bearer "+el("ai-key").value}},null,2));
el("rename-player").onclick=()=>{el("new-name").value=state.data.self.result.name;el("rename-dialog").showModal()};
el("save-name").onclick=async()=>{try{await act("cultivator_ops","rename "+JSON.stringify(el("new-name").value));el("rename-dialog").close()}catch(error){el("rename-error").textContent=error.message}};
if(state.key)refresh().catch(error=>el("entry-error").textContent=error.message);
setInterval(()=>{if(state.key&&!state.busy&&!document.hidden)refresh().catch(()=>{});},5000);
