"use strict";
const el=id=>document.getElementById(id);
const routes={qingxiao:"剑先问心，再问敌。以实战磨剑，走单体爆发之路。",xuanheng:"天地有序，万物可解。布阵、制符，提前准备再入险境。",danxia:"药可以救人，也可以杀人。炼丹、医修与灵植相伴。",fuyao:"深入荒岭，与灵兽同行。在狩猎与共存之间作出选择。",rogue:"无门无派，自由入世。靠信誉、残卷与奇遇寻道。"};
const names={sect:"宗门",town:"青石镇",wild:"落霞山野",realm:"灵溪秘境"};
const itemNames={"herb": "灵草", "potion": "回气丹", "foundation_pill": "筑基丹", "golden_pill": "结金丹", "soul_pill": "凝婴丹", "iron": "玄铁", "core": "灵核", "fang": "狼牙", "sword": "青云剑", "armor": "玄铁甲", "charm": "清心佩", "talisman": "护身法宝", "manual": "长春功卷", "sword_manual": "青云剑经", "array_flag": "阵旗", "paper_talisman": "基础符箓", "mechanism_part": "机关零件", "scrap": "废丹", "relic_fragment": "遗迹残片", "forbidden_sword": "禁录邪剑残卷", "forbidden_pill": "禁丹", "protected_core": "保护种群兽核", "potion_fine": "回气丹·良品", "potion_superior": "回气丹·上品", "foundation_pill_fine": "筑基丹·良品", "foundation_pill_superior": "筑基丹·上品", "golden_pill_fine": "结金丹·良品", "golden_pill_superior": "结金丹·上品", "soul_pill_fine": "凝婴丹·良品", "soul_pill_superior": "凝婴丹·上品", "core_array_chart": "玄衡核心阵图"};
let key=sessionStorage.getItem("qingyun-key")||"",state=null,busy=false;
function toast(message){el("toast").textContent=message;el("toast").hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el("toast").hidden=true,5000)}
async function request(path,payload,token=key){const response=await fetch(path,{method:payload?"POST":"GET",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},...(payload?{body:JSON.stringify(payload)}:{})});const data=await response.json();if(!response.ok||data.ok===false)throw Error(data.error||"这次行动未能完成");return data}
function button(label,tool,args,disabled=false){const b=document.createElement("button");b.textContent=label;b.disabled=disabled||!!state?.readOnly;b.onclick=()=>act(tool,args);return b}
function row(container,title,note,buttons=[]){const node=document.createElement("div");node.className="row";const text=document.createElement("span");text.textContent=title;if(note){const small=document.createElement("small");small.textContent=note;text.append(small)}node.append(text,...buttons);container.append(node)}
async function refresh(){state=await request("/api/state");render()}
async function act(tool,args={}){if(busy||state?.readOnly)return;busy=true;el("game").setAttribute("aria-busy","true");try{const data=await request("/api/action",{tool,arguments:args});const line=document.createElement("p");line.textContent=actionNames[tool]||"行旅";const detail=document.createElement("small");detail.textContent=" · "+describe(data.result);line.append(detail);el("log").prepend(line);await refresh()}catch(error){toast(error.message)}finally{busy=false;el("game").setAttribute("aria-busy","false")}}
const actionNames={rename:"修改道号",cultivate:"静心修炼",explore:"探索周围",breakthrough:"尝试突破",retreat:"闭关休养",travel:"前往新地点",talk:"与人交谈",fight:"开始斗法",use_skill:"施展招式",use_item:"使用物品",accept_quest:"接下委托",submit_quest:"交付委托",trade:"坊市交易"};
function describe(result){if(typeof result==="string")return result;if(!result)return"行动已完成";if(result.previousName!==undefined)return result.previousName+" → "+result.name;return result.message||result.text||result.dialogue||result.description||(result.gained!==undefined?"修为增加 "+result.gained:result.winner?"战斗结束："+result.winner:"行动已记入仙途")}
function render(){const p=state.self.result,w=state.world.result;el("watch-note").hidden=!state.readOnly;el("welcome").hidden=true;el("game").hidden=false;el("logout").hidden=false;el("player-name").textContent=p.name;el("clock").textContent="第 "+w.time.day+" 日 · "+w.time.hour+" 时 · "+(routes[p.route]?el("route").querySelector('[value="'+p.route+'"]').textContent.split(" · ")[0]:"尚未择道");
el("metrics").replaceChildren();for(const [label,value]of[["境界",p.realm+" · "+p.realmStage],["修为",p.cultivation+" / "+p.cultivationRequired],["灵根与资质",p.root+" · 资质 "+p.aptitude+"/5"],["气血",p.hp+" / "+p.max_hp],["灵力",p.qi+" / "+p.maxQi],["灵石",p.stones]]){const node=document.createElement("div");node.className="metric";const small=document.createElement("small"),strong=document.createElement("strong");small.textContent=label;strong.textContent=value;node.append(small,strong);el("metrics").append(node)}
el("location-name").textContent=w.location.name||names[w.region];el("description").textContent=w.location.description||"山川有灵，每一步都通向新的见闻。";
for(const id of["actions","exits","npcs","quests","enemies","skills","inventory","shop"])el(id).replaceChildren();
const available=w.nearbyActions||[];for(const [tool,args]of[["cultivate",{method:p.method,duration:1}],["explore",{}],["breakthrough",{}],["retreat",{duration:8}]])if(available.includes(tool))el("actions").append(button(actionNames[tool],tool,args));
if(!p.route)for(const id of Object.keys(routes))el("actions").append(button(el("route").querySelector('[value="'+id+'"]').textContent.split(" · ")[0],"choose_route",{route:id}));
for(const destination of w.location.exits||[])el("exits").append(button(names[destination]||destination,"travel",{destination},!!p.battle));
for(const[id,npc]of Object.entries(w.npcs||{}))row(el("npcs"),npc.name,npc.identity||"",[button("问候","talk",{npc:id,topic:"greeting"}),button("求教","talk",{npc:id,topic:"teach"})]);
for(const[id,q]of Object.entries(w.quests||{}))row(el("quests"),q.name,q.description,[button("接取","accept_quest",{quest:id}),button("交付","submit_quest",{quest:id})]);
for(const[id,e]of Object.entries(w.enemies||{}))row(el("enemies"),e.name,"历练对手",[button("挑战","fight",{target:id},!!p.battle)]);
if(p.battle){row(el("enemies"),"斗法进行中","选择招式，或撤离战场",[button("撤离","retreat",{})])}
for(const[id,s]of Object.entries(w.skills||{}))row(el("skills"),s.name,"灵力 "+s.cost+" · "+({attack:"攻击",defense:"防御",heal:"回复",control:"控制",haste:"提速",movement:"身法",buff:"增益",debuff:"减益"}[s.type]||s.type),[button("施展","use_skill",{skill:id},!p.battle)]);
for(const[id,count]of Object.entries(p.inventory||{}))row(el("inventory"),itemNames[id]||id,"数量 "+count,[button("使用","use_item",{item:id})]);
if(state.readOnly){el("log").replaceChildren();for(const entry of [...(state.history?.result||[])].reverse()){const line=document.createElement("p");line.textContent="第 "+(Math.floor(entry.time/1440)+1)+" 日 · "+(actionNames[entry.action]||"修行")+" · "+describe(entry.result);el("log").append(line)}if(!el("log").children.length)row(el("log"),"这位修士尚未开始历练","AI 的行动会自动出现在这里");}
for(const[id,item]of Object.entries(w.shop||{}))row(el("shop"),item.name||itemNames[id]||id,(typeof item==="number"?item:(item.price??item.buyPrice??""))+" 灵石",[button("购买","trade",{item:id,quantity:1,side:"buy"})]);}
el("route").onchange=()=>el("route-note").textContent=routes[el("route").value];el("route").onchange();
el("register").onclick=async()=>{try{const data=await request("/api/register",{name:el("name").value,kind:"human",route:el("route").value},"");key=data.api_key;sessionStorage.setItem("qingyun-key",key);await refresh();toast("角色已创建。请点击保存我的凭证，留一份副本。")}catch(error){el("entry-error").textContent=error.message}};
el("login").onclick=async()=>{try{key=el("key").value.trim();await refresh();sessionStorage.setItem("qingyun-key",key)}catch(error){el("entry-error").textContent=error.message}};
el("logout").onclick=()=>{state=null;key="";sessionStorage.removeItem("qingyun-key");el("game").hidden=true;el("welcome").hidden=false;el("logout").hidden=true;el("key").value=""};
el("open-ai").onclick=()=>el("ai-dialog").showModal();
el("register-ai").onclick=async()=>{try{const data=await request("/api/register",{name:el("ai-name").value,kind:"ai"},"");el("ai-key").value=data.api_key;el("ai-url").value=location.origin+"/mcp/?api_key="+encodeURIComponent(data.api_key);el("ai-result").hidden=false;el("ai-error").textContent=""}catch(error){el("ai-error").textContent=error.message}};
async function copy(value){try{await navigator.clipboard.writeText(value);toast("已复制，请妥善保存。")}catch{toast("复制不可用，请手动选中保存。")}}
el("rename-player").onclick=()=>{el("new-name").value=state.self.result.name;el("rename-error").textContent="";el("rename-dialog").showModal()};
el("save-name").onclick=async()=>{try{await request("/api/rename",{name:el("new-name").value});await refresh();el("rename-dialog").close();toast("道号已修改，凭证和进度保留。")}catch(error){el("rename-error").textContent=error.message}};
el("copy-key").onclick=()=>copy(key);el("copy-ai").onclick=()=>copy(el("ai-url").value);
if(key)refresh().catch(error=>{el("entry-error").textContent=error.message});

setInterval(()=>{if(key&&state?.readOnly&&!busy&&!document.hidden)refresh().catch(error=>toast(error.message));},5000);
